version: '3'
services:
  api: &node_app
    image: node:12.17-stretch
    command: npm start
    working_dir: /app/api
    depends_on:
      - db
      - redis
    env_file:
      - ./api/.env
    ports:
      - '8090:8090'
    volumes:
      - .:/app

  queue:
    <<: *node_app
    command: npm run queue
    ports:
      - '8090'

  db:
    image: postgres:12.1-alpine
    env_file:
      - ./api/.env
    ports:
      - '5432:5432'

  redis:
    image: redis:5.0.6-alpine

  web:
    image: node:12.17-stretch
    command: npm start
    working_dir: /app/web
    depends_on:
      - api
    ports:
      - '8080:8080'
    volumes:
      - .:/app
