openapi: 3.0.1
info:
  title: MailTeam Gmail Addon API
  description: Part of the MailTeam system, providing server support for MailTeam Gmail Addon
  version: 1.0.0
servers:
  - url: http://localhost:8080
  - url: http://dev.apollo.codequest.com
components:
paths:
  /test/test:
    summary: Test endpoint
    get:
      responses:
        200:
          description:
            All is fine
      tags:
        - test
